default:
  image: debian:11
  tags: 
    - loki.tel

stages:
  - build

variables:
  PUPPETMASTER: "mcp.loki.tel"

cache:
  paths:
    - vendor/ruby

before_script:
  - export DEBIAN_FRONTEND="noninteractive"
  - apt-get update
  - apt-get -y install wget sudo openssl gnupg lsb-release python3-dev

dependencies:
  stage: build
  script:
    - bash -x deploy.sh
